### ISSUE TITLE
Load Vega and Vega-Lite versions based on the spec

### ISSUE THREAD

**Issue by domoritz** [vega/vega-render-service#12]
Right now, we only support the Vega or Vega-Lite version that is installed but it would be nice to support any version referenced in the spec.

**Comment by hungngo97** [comment]
Any recommended way to load Vega versions dynamically?

**Comment by domoritz** [comment]
I'm not sure how to do it in node. We have all versions on NPM and https://www.jsdelivr.com/package/npm/vega. 

While I think it would be nice eventually, I think we should wait with this until https://github.com/vega/editor/issues/336 is fixed. 

Let's close this issue for now.
